on: [push, pull_request]
name: build + test
jobs:
  build:
    strategy:
      matrix:
        dotnet: [3.1.300]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Dotnet ${{ matrix.dotnet }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build solution
        run: dotnet build
      - name: Test solution
        run: dotnet test
